Added Javadocs to remaining classes.
Terasology/Books pull request #18
Opened 2018-10-25 23:58 UTC by PAndaContron

Javadocs have been added to:

- BookcaseComponent
- BookComponent
- BookRecipeComponent
- DefaultDocumentData
- PageEditor
- RecipeParagraph

2018-10-26 15:01 UTC, mjuvekar7 requested changes

2018-10-26 15:01 UTC, mjuvekar7 commented on src/main/java/org/terasology/books/DefaultDocumentData.java
> +     */
You need to add `@param` annotations describing each parameter required by the method/constructor.

2018-10-26 15:01 UTC, mjuvekar7 commented on src/main/java/org/terasology/books/DefaultDocumentData.java
> +     */
Parameter description required

2018-10-26 15:01 UTC, mjuvekar7 commented on src/main/java/org/terasology/books/DefaultDocumentData.java
> +     */
Parameter description required

2018-10-26 15:01 UTC, mjuvekar7 commented on src/main/java/org/terasology/books/RecipeParagraph.java
> +     * This paragraph's horizontal alignment will always be centered.
This description doesn't actually describe what the method does. You should describe the method as something that gets the paragraph render style. Then in a second sentence you could say something like "note that this paragraph's horizontal alignment will always be centered"

2018-10-26 15:01 UTC, mjuvekar7 commented on src/main/java/org/terasology/books/RecipeParagraph.java
> +     * {@inheritDoc}
I would prefer if you didn't inheritDoc here. For most modules, we don't actually compile the Javadoc. The Javadocs are there mostly for people reading the code. So for someone reading this file, the inheritDoc could be a bit annoying (definitely not descriptive).

2018-10-26 15:01 UTC, mjuvekar7 commented on src/main/java/org/terasology/books/RecipeParagraph.java
> +     * @param defaultStyle Not used
Needs method description

2018-10-26 15:01 UTC, mjuvekar7 commented on src/main/java/org/terasology/books/RecipeParagraph.java
> +     * @param defaultStyle Not used
Method description and `@return` missing

2018-10-26 15:01 UTC, mjuvekar7 commented on src/main/java/org/terasology/books/DefaultDocumentData.java
> +     * Gets an unmodifiable list of the paragraphs on this page.
Needs `@return` description

2018-10-26 15:01 UTC, mjuvekar7 commented on src/main/java/org/terasology/books/RecipeParagraph.java
> +     */
Needs `@return`

2018-10-26 15:01 UTC, mjuvekar7 commented on src/main/java/org/terasology/books/RecipeParagraph.java
> +     */
Needs `@return`

2018-10-26 15:01 UTC, mjuvekar7 commented on src/main/java/org/terasology/books/logic/BookRecipeComponent.java
> + * Used in a prefab to represent a recipe. The prefab can then be inserted in a book using a &ltrecipe&gt tag inside a page as such:
Please get rid of the `&lt` and `&gt`. They will probably work if the Javadocs are compiled, but they make for bad readability

2018-10-26 15:01 UTC, mjuvekar7 commented on src/main/java/org/terasology/books/logic/BookRecipeComponent.java
> + * <code>&ltrecipe module:prefab&gt</code>
Again, I would prefer if you got rid of the &lt/gt

2018-10-26 15:19 UTC, PAndaContron commented
Ok, I will make sure to change these. Most of the tags are missing because I was under the impression that the Javadocs will  be compiled (I use Eclipse so it does that automatically on the side), so they would be inherited. I'll fix it when I get home.

2018-12-24 05:47 UTC, merged

2018-12-24 05:49 UTC, Waterpicker commented
Approved after I dealt with a merge conflict.